### ISSUE TITLE
[pages]回答ページの作成

### ISSUE THREAD

**Issue by junki3737** [musicangora/hacku-team05-hoge#10]
## 確認！

- [x] 優先度のラベルを設定した

## 課題の内容
回答ページの作成（フェーズ︙３）

## 課題の完了定義
各要素の設置＆処理の実装完了

## 補足
特に問題なければブランチ名は「feature/10」でお願いします
プルリクは自分以外のフロント担当でお願いします。
junki3737 or r5Rin or selva604
何か気になること等ありましたら、Slackでお願いします。

**Comment by r5Rin** [comment]
一応書けたのですが、
こちらの環境だとお題収集に入るとこで404が出ちゃうので動作確認はできでません・・・。
岩本さんの環境で動かしてみてどうなるか見ていただきたいです

**Comment by junki3737** [comment]
了解です
/:id/thinkanserで直接画面は見れますよー
