### ISSUE TITLE
ニックネーム登録後の表示

### ISSUE THREAD

**Issue by junki3737** [musicangora/hacku-team05-hoge#43]
## 確認！

- [x] 優先度のラベルを設定した

## 課題の内容
ゲストがニックネームを登録したら,
「ホストがケームを開始するまで少々お待ち下さい」
を表示する。

**Comment by r5Rin** [comment]
もう一度！で部屋を立てた処理で_idのindex.vueのニックネーム登録まわりをいじるので同時に修正します

**Comment by junki3737** [comment]
ありがとうございます！
