### ISSUE TITLE
listpanelコンポーネントの投票数の見た目

### ISSUE THREAD

**Issue by r5Rin** [musicangora/hacku-team05-hoge#51]
## 確認！

- [ ] 優先度のラベルを設定した

## 課題の内容
急ぎで追加したのでspanで表示してるだけなのでもうちょっと良い見た目にしたい

**Comment by musicangora** [comment]
## 修正対応します
ListPanelコンポーネントでどうしてもやりたかったことあるので、今日中にいけそうなら合わせて実装しておきます

間に合いそうならレビューとマージお願いします:pray:

## TODO
- 投票数の見た目の調整
- transform を使わずflex justify-centerで位置合わせ
- ボタンアニメーションの追加

**Comment by junki3737** [comment]
bug fixでいいねボタンの右に投票数を持っていきました（Figmaのように下には持っていけなかった笑）
元々、今日お時間取れないことは知っているので、お手隙の時間が取れればで構わないので、ブランチの更新後対応をお願いします
