### ISSUE TITLE
_id/index.vueの招待リンクコピー周りの修正

### ISSUE THREAD

**Issue by musicangora** [musicangora/hacku-team05-hoge#58]
## 課題の内容
- 招待リンクをコピーする時にthis.pageUrlをコピーしてるので、ゲームについての説明を入れてもコピーされてない
- ゲームの紹介文の「表示」は不要な気がする
- ゲーム紹介文はコピーされるリテラルだけにあれば良い気がする
- 「コピーされたよ」にスタイルを当てる

## 課題の完了定義
- リンクのコピーが、URLのみ表示、クリップボードに紹介文込みでコピされている
- コピー時の「コピーしました」にスタイルが適用されている

## 補足
いけそうならやります

**Comment by selva604** [comment]
ゲームの紹介はMetatagでできるので、故意的にthis.pageUrlのみコピーしています

**Comment by musicangora** [comment]
ありがとうございます！
そういうことなんですね、じゃあゲームの紹介の[文章の表示](https://github.com/musicangora/hacku-team05-hoge/blob/df7a122509a4df741d119b11a6652fc1183291f2/pages/_id/index.vue#L90)消しちゃってもいいですかね
本来文章入れるつもりでデザインしてなかったので想定してなかったので……

**Comment by selva604** [comment]
消しちゃいましょう！
