### ISSUE TITLE
[投票ページ]: お題と回答で挙動が異なる

### ISSUE THREAD

**Issue by junki3737** [musicangora/hacku-team05-hoge#60]
## バグをみつけた URL
:id/decideQuestion
:id/decideAnser

## バグの概要
- 回答投票ページで残り投票数、現在の投票数が表示されない
- 回答投票ページの一覧表示部分が「みんなが考えたお題」になっている
- 定期的にバックエンドに問い合わせて、投票数を表示しているが返ってくるのは全投票数であるため他人の投票状況がばれている(投票の偏りを防ぐため表示するのは自分の投票数のみの予定だったような)

## 再現方法
ページへのアクセス

## 原因
this.の参照先の違いかな？？

## 完了定義
- 回答投票でも同様に投票状況が反映される
- 回答投票ページの一覧表示部分が「みんなが考えた回答」になる
- 自分の投票状況のみ反映されるようになる

**Comment by musicangora** [comment]
> 回答投票ページの一覧表示部分が「みんなが考えたお題」になっている

コンポーネント化したときに、decideQuestionをコピペしたので起きたんだと思います。申し訳ないです🙏

decideAnser/index.vue内の[該当箇所](https://github.com/musicangora/hacku-team05-hoge/blob/df7a122509a4df741d119b11a6652fc1183291f2/pages/_id/decideAnser/index.vue#L20)を「みんなの回答」に変更するだけで修正できると思います。

**Comment by junki3737** [comment]
了解です

**Comment by r5Rin** [comment]
他の人の見れるようにしたのは確認不足でした…
自分の投票数のみの表示なら定期的なバックエンド問い合わせも必要ないですけど、decideAnswerに入るタイミングでクライアント間の差があると、先に遷移した側で遅れているほうの回答を表示できない可能性があるので、読み込みの何秒か後に回答一覧を自動でリロードする処理も作っていただけると助かります
(タイマーずれ修正が機能していればおおむね3秒以内の差になるので、5秒後くらい)

**Comment by junki3737** [comment]
一応、回答一覧の表示は回答がメンバー全員文揃ったら(.lengthで判定)表示するようになってるので、一旦それでいかがでしょうか？
途中で誰か退出したら、、、リロード、、、、とかバグありそうですけど

**Comment by r5Rin** [comment]
表示方法lengthの判定なら大丈夫そうです！
助かります～

**Comment by junki3737** [comment]
了解です　ありがとうございます
